import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, ArrowDown, Github, Linkedin, Mail, FileText } from 'lucide-react';

const projects = [
  { name: 'SmartProBono', category: 'PRODUCT ENGINEERING · LEGAL TECH', description: 'A Legal + IP preparation platform that turns complex questions into structured next steps.', detail: 'Built guided Legal + IP intake, readiness profiles, document preparation, account workflows, and professional handoff around the Learn → Prepare → Connect model.', engineering: 'Next.js workflows backed by Supabase and PostgreSQL, structured APIs, authenticated ownership, and a rule-based generation fallback so core preparation still works without an AI provider.', stack: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL'], url: 'https://smartprobono.org', code: 'https://github.com/BTheCoderr/smartprobonoip', color: 'mint', number: '01' },
  { name: 'Praxis OT', category: 'FULL STACK · EDUCATION WORKFLOWS', description: 'A school-based occupational therapy evaluation workspace from assessment through report preparation.', detail: 'Built structured intake, evidence review, clinical reasoning support, report preparation, and evaluation PDF exports for school-based occupational therapists.', engineering: 'Supabase authentication, PostgreSQL, private storage, provider fallbacks, and a separate fictional sample workspace for safe product review.', stack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Supabase Auth'], url: 'https://usepraxisot.com', code: null, color: 'lavender', number: '02' },
  { name: 'Show Your Hand', category: 'INTERACTIVE APPLICATION · REALTIME GAME LOGIC', description: 'An original card game translated into solo play and online 1v1 multiplayer.', detail: 'Built solo matches against computer opponents plus online 1v1 play with scoring, targeted actions, defensive responses, and turn resolution.', engineering: 'Server-controlled multiplayer state keeps each player’s hand private while Supabase Edge Functions validate game actions; the shared rules engine handles counters, refills, scoring, and deck recycling.', stack: ['React', 'TypeScript', 'Supabase', 'Edge Functions', 'PWA'], url: 'https://show-your-hand.netlify.app', code: 'https://github.com/BTheCoderr/show-your-hand', color: 'peach', number: '03' },
];
const skills = [
  ['Interfaces', 'React, Next.js, TypeScript, JavaScript, Tailwind CSS, responsive layouts'],
  ['Services & data', 'Node.js, REST APIs, Supabase, PostgreSQL, authentication'],
  ['Delivery', 'Git, GitHub, Netlify, debugging, QA, production support'],
];
export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header wrap"><a className="wordmark" href="#top" aria-label="Baheem Ferrell home">bf<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#experience">Experience</a><Link href="/resume">Résumé</Link><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={15}/></a></nav></header>
    <main id="main">
      <section id="top" className="hero wrap">
        <div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> OPEN TO SOFTWARE ENGINEERING ROLES</p><p className="intro">Hi, I’m Baheem Ferrell.</p><h1>I build software<br/>that people<br/><span>can put to work.</span></h1><p className="hero-description">Full-stack software engineer building web applications with React, Next.js, TypeScript, and PostgreSQL. From the first workflow to the production release.</p><div className="actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={17}/></a><Link className="button secondary" href="/resume"><FileText size={17}/> View résumé</Link></div><p className="location">Based in Providence, Rhode Island</p></div>
        <aside className="profile-panel"><div className="portrait"><Image src="/profile-photo.JPG" alt="Baheem Ferrell" fill sizes="(max-width: 760px) 85vw, 380px" priority/></div><div className="profile-caption"><span>ENGINEER. BUILDER. PROBLEM SOLVER.</span><div className="profile-links"><a href="https://github.com/BTheCoderr" aria-label="Baheem on GitHub"><Github size={20}/></a><a href="https://www.linkedin.com/in/baheem-ferrell-866122101/" aria-label="Baheem on LinkedIn"><Linkedin size={20}/></a><a href="mailto:bferrell514@gmail.com" aria-label="Email Baheem"><Mail size={20}/></a></div></div><p className="panel-note">Thoughtful interfaces.<br/>Reliable workflows.<br/>Ownership from end to end.</p></aside>
      </section>
      <div className="stack-strip"><div className="wrap"><span>MY CORE TOOLKIT</span><p>React <i>/</i> Next.js <i>/</i> TypeScript <i>/</i> PostgreSQL <i>/</i> Supabase</p></div></div>
      <section id="work" className="section wrap"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Real problems.<br/>Working software.</h2></div><p>A closer look at the applications I build and the engineering behind them.</p></div><div className="projects">{projects.map(p=><article className="project" key={p.name}><div className={`project-title ${p.color}`}><span className="project-number">{p.number}</span><div><p className="eyebrow">{p.category}</p><h3>{p.name}</h3><p>{p.description}</p></div><a className="project-title-arrow" href={p.url} aria-label={`Open ${p.name}`}><ArrowUpRight size={32} aria-hidden="true"/></a></div><div className="project-body"><p>{p.detail}</p><h4>Engineering focus</h4><p>{p.engineering}</p><ul className="tags" aria-label="Technologies and capabilities">{p.stack.map(s=><li key={s}>{s}</li>)}</ul><div className="project-links"><a href={p.url}>View application <ArrowUpRight size={16}/></a>{p.code ? <a href={p.code}><Github size={16}/> Source code</a> : <span>Private repository</span>}</div></div></article>)}</div></section>
      <section id="experience" className="experience section"><div className="wrap experience-grid"><div><p className="eyebrow">02 / EXPERIENCE</p><h2>Building products.<br/>Solving production<br/>problems.</h2><p className="section-description">My background combines independent product development with enterprise software support and team-based development.</p><Link className="text-link" href="/resume">Read my résumé <ArrowUpRight size={18}/></Link></div><div className="timeline"><article><p className="date">2025 — PRESENT</p><h3>SmartProBono</h3><p className="role">Founder · Product engineering</p><p>Own application workflows, interface development, integrations, and releases for a Legal + IP preparation platform.</p></article><article><p className="date">2021 — PRESENT</p><h3>Independent development</h3><p className="role">Full-stack web applications & client projects</p><p>Translate requirements into responsive applications and websites, then handle deployment, debugging, and iteration.</p></article><article><p className="date">2022 — 2025</p><h3>MEDITECH</h3><p className="role">Software Support Specialist</p><p>Investigated enterprise healthcare software issues, reproduced failures, and coordinated resolutions with customers and engineering teams.</p></article><article><p className="date">2019 — 2021</p><h3>MojoTech</h3><p className="role">Software Development Intern</p><p>Contributed to web application features, debugging, testing, and team development workflows.</p></article></div></div></section>
      <section id="skills" className="section wrap"><p className="eyebrow">03 / HOW I BUILD</p><h2>Practical tools.<br/>End-to-end ownership.</h2><div className="skills-grid">{skills.map(([title,body],i)=><article key={title}><span className="skill-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="education"><span>EDUCATION</span><p>University of Rhode Island<br/><strong>B.A., Computer & Data Science</strong></p></div></section>
      <section id="contact" className="contact wrap"><p className="eyebrow">LET’S BUILD SOMETHING USEFUL</p><h2>Looking for an engineer<br/>who owns the work?</h2><p>I’m interested in software engineering roles focused on useful products, thoughtful interfaces, and reliable systems.</p><a className="button primary" href="mailto:bferrell514@gmail.com">Email me <ArrowUpRight size={18}/></a><a className="email" href="mailto:bferrell514@gmail.com">bferrell514@gmail.com</a></section>
    </main><footer className="wrap footer"><span>© {new Date().getFullYear()} Baheem Ferrell</span><div><a href="https://github.com/BTheCoderr">GitHub</a><a href="https://www.linkedin.com/in/baheem-ferrell-866122101/">LinkedIn</a><Link href="/resume">Résumé</Link></div></footer>
  </>;
}
